plugins:
  bilibili_onebox_enabled:
    default: true
    client: true
  bilibili_onebox_cache_duration:
    default: 86400
    client: false
  bilibili_onebox_resolve_short_links:
    default: true
    client: true
  bilibili_onebox_resolve_live_short_ids:
    default: true
    client: true
